### ISSUE TITLE
404 not found.

### ISSUE THREAD

**Issue by amanuel2** [hpssjellis/bash-android-cloud9#1]
Alright so i set it up in cloud9ide. Then when i click on index.html to run it i get this page:

http://i.imgur.com/cVQ33H6.png

Then after when i click that link to set up android i get this:

http://i.imgur.com/OsWndRW.png

**Comment by hpssjellis** [comment]
Fixed it. 
Big help having someone check these sites as everytime I change one little thing it can affect several files.
