### ISSUE TITLE
failing setup.sh

### ISSUE THREAD

**Issue by gpolic** [hpssjellis/bash-android-cloud9#5]
Not sure if there is a problem. This trouble maybe because I am completely new to this coding stuff.
I have a already existing workspace in Cloud9 in which i did "git clone" on this project
That was a empty workspace and it was not created with the option to clone a project from Cloud9 panel. The workspace in Cloud9 was created a few month ago. So I did clone the project manually.

Execute setup.sh failed on the following command:
`wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O - | tar -xvf -`

So I did comment this line, and uncommented the other lines

```

wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O /home/ubuntu/workspace/android-sdk_r24.4.1-linux.tgz
tar -xvzf /home/ubuntu/workspace/android-sdk_r24.4.1-linux.tgz -C /home/ubuntu/workspace/
rm android-sdk_r24.4.1-linux.tgz


#submitted by ismail-s faster way to do the above
#wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O - | tar -xvf -


chmod a+x android-sdk_r24.4.1-linux.bin
./android-sdk_r24.4.1-linux.bin

#rm android-sdk_r24.4.1-linux.bin
```

Also in the end of the script the last commands failed:
bash a00-auto-ant-gradle.sh

The script is inside a folder and it could not run from the "root".
I did it on the terminal and it worked after I switched to that folder.

On the scipt a02 to create a gradle project I changed the folder path:

```

echo "Enter a folder name, no spaces, no dashes, underscore allowed, for your app and folder example: helloGradle"
read wow4


ls -l /home/ubuntu/workspace/android-sdk-linux/platforms

```

it seems to work now, as the example was created and the apk files are created.
I cannot get apache working so far but that is not so important.

**Comment by gpolic** [comment]
For the apache. 
in my apache folder there was no "log" folder. I created it and it looks fine now, no more errors.

Also click on "Share" on cloud 9 IDE and now I have my page working on the browser :-)))

**Comment by hpssjellis** [comment]
someone just push requested that change, so I will try to change it back. Thanks for the heads up.

**Comment by hpssjellis** [comment]
By the way, this repo is for testing my workspace for android online at cloud9. The conversation is at  https://community.c9.io/t/android-sdk-workspace-template/1304/53  The dockerfile is fully made just cloud9 needs to compile it. Any comments about this being useful may help get them to bump up the priority.

**Comment by gpolic** [comment]
yes of course it is helpful ! are u kidding !
The reason they are not doing it yet?  I dont know !

I read that conversation yesterday, although I did not comment. I will do so

Congrats for your work. It is really very helpful.  I see you're dealing with some interesting stuff
