### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Eulerianial** [hpssjellis/bash-android-cloud9#8]
If I want to build the below app through this setup, can I do it:
https://github.com/savs95/Android-Virtual-Reality/tree/master/AndroidVR

Best,
Vijay

**Comment by hpssjellis** [comment]
I can't tell if it is build using gradle or ant. But it is an eclipse project so probably best to fully setup eclipse. Must be a video somewhere showing how to do that on you type of machine.
